-- Drop table user_directory;
CREATE TABLE IF NOT EXISTS user_directory(
    "ID" BIGINT NOT NULL,
    "PARENT_ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255) NOT NULL,
    "FILE_TYPE" CHARACTER VARYING(255) NOT NULL,
    "CREATED_DATE" TIMESTAMP NOT NULL
);